name: Terraform Prerequisites

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint_and_security_checks:
    name: Lint and Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint

      - name: Initialize TFLint
        shell: bash
        run: tflint --init

      - name: Run TFLint on all modules
        shell: bash
        run: |
          for dir in $(find ./modules -type d); do
            echo "Running TFLint on $dir"
            tflint --chdir="$dir" --recursive || true
          done

      - name: Run TFsec on all modules
        shell: bash
        run: |
          for dir in $(find ./modules -type d); do
            echo "Running TFsec on $dir"
            tfsec "$dir" || true
          done
